version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/chlog/
    binary: chlog
    ldflags:
      - -s -w
      - -X github.com/ariel-frischer/chlog/internal/version.Version={{.Version}}
      - -X github.com/ariel-frischer/chlog/internal/version.Commit={{.ShortCommit}}
      - -X github.com/ariel-frischer/chlog/internal/version.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  github:
    owner: ariel-frischer
    name: chlog
